### ISSUE TITLE
get TUI working again on staking network

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony-tui#24]
We may need to have another branch or so to support master branch , the OSTN. I assume there are quite a lot of incompatible changes between master and s3 (mainnet).  So, it is better to have another branch.  Maybe backup current code to s3 branch.

**Comment by LeoHChen** [comment]
additional data can be extracted from the RPC of the node, like, some of them are already there.

* know his own status and how to fix any problem: 
* binary version, leveldb state, block sync
* network condition, message loss, critical errors, consensus stages
* delegated stakes, voting power, median stake change
* election results, epoch committees, accumulated rewards

**Comment by stephen-tse** [comment]
@fxfactorial @AndyBoWu the diagnostics script like this across all nodes (not TUI) can be very helpful for debugging shard down

**Comment by rhazberries** [comment]
Staking added with #29
